Sources/AppDelegate.swift, Sources/Controller/MainViewController.swift
#7 
> 구현 내용 및 작업 했던 내역
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/61077215/186b14be-3696-4be8-a51c-a901d951339f
<br/>
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
- Swift 어렵네요.. 응애 👶
<br/><br/>
=> [Feat] #7 집중 타이머 간단 화면 구현

Sources/App/AppDelegate.swift, Sources/MainScene/ViewControllers/MainViewController.swift
#16 
> 구현 내용 및 작업 했던 내역
<br/>
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
<br/><br/>
=> [Feat] #16 Timer 작동중 하단 라벨 기능 추가

Sources/DashBoardScene/ViewControllers/DayViewController.swift, Sources/DashBoardScene/Views/CompositionalCell.swift, Sources/DashBoardScene/Views/MockData.swift
#21 
> 구현 내용 및 작업 했던 내역
<br/>
> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
- 재밌었습니다....
<br/><br/>
=> [대시보드] 2,3 전체통계

Sources/MainScene/ViewControllers/TagModalViewController.swift
=> Revert "[Fix] 태그 모달 컬렉션뷰 1 line 2 Cell"

Sources/DashBoardScene/Views/CompositionalCell.swift, Sources/DashBoardScene/Views/MockData.swift, Sources/Model/DashBoard.swift, Sources/Model/Option.swift, Sources/Model/Pomodoro.swift, Sources/Model/TagList.swift, Sources/SettingsScene/ViewControllers/LongBreakModalViewController.swift, Sources/SettingsScene/ViewControllers/SettingViewController.swift, Sources/SettingsScene/ViewControllers/ShortBreakModalViewController.swift, Sources/UIColor+HexCode.swift
- 저장할 데이터 정의 및 모델 구현
> 구현해야하는 이슈 체크리스트
DB 모델을 적긴 했는데.. 너무 플러터스럽게 적은거 같기도 하고.. 제 뇌피셜로 정의해서 좀 수정이 필요할 수도 있을거 같네요...
=> [Feat] DB 정의, 데이터모델 설계 (Realm X)

Sources/DashBoardScene/Views/CompositionalCell.swift, Sources/DashBoardScene/Views/MockData.swift, Sources/Model/DashBoard.swift, Sources/Model/Option.swift, Sources/Model/Pomodoro.swift, Sources/Model/TagList.swift, Sources/SettingsScene/ViewControllers/LongBreakModalViewController.swift, Sources/SettingsScene/ViewControllers/SettingViewController.swift, Sources/SettingsScene/ViewControllers/ShortBreakModalViewController.swift, Sources/UIColor+HexCode.swift
close #68 
<br>
> 구현해야하는 이슈 체크리스트
많이 헤매느라 늦었습니다. 죄송해요..
=> [Feat] #68 짧은 휴식 설정창 구현

Sources/DashBoardScene/Views/CompositionalCell.swift, Sources/DashBoardScene/Views/MockData.swift, Sources/Model/DashBoard.swift, Sources/Model/Option.swift, Sources/Model/Pomodoro.swift, Sources/Model/TagList.swift, Sources/SettingsScene/ViewControllers/LongBreakModalViewController.swift, Sources/SettingsScene/ViewControllers/SettingViewController.swift, Sources/SettingsScene/ViewControllers/ShortBreakModalViewController.swift, Sources/UIColor+HexCode.swift
close #63  
긴 휴식을 설정할 수 있는 설정화면
<br>
> 구현해야하는 이슈 체크리스트
짧은 휴식 창과 거의 동일합니다
=> [Feat] #63 긴 휴식 설정창 구현

Pomodoro.xcodeproj/project.pbxproj, Sources/MainScene/View/TimerCollectionViewCell.swift, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TimeSettingViewController.swift, Sources/MainScene/Views/TimerCollectionViewCell.swift
https://github.com/HGU-iOS-Study-Group/Pomodoro/pull/98
여기서 필요한 파일만 가져와서 다시 PR 합니다.
=> [Feat] 시간 설정 수평스크롤 구현

Sources/DashBoardScene/ViewControllers/WeekViewController.swift, Sources/DashBoardScene/Views/DashboardStatusCell.swift
close #93 
선택 날짜를 기준으로 해당 날짜가 속한 시작 날짜와 끝 날짜를 가져와 화면에 보여준다.
<br>
구현해야하는 이슈 체크리스트
=> [Feat] Week_주차별 날짜 라벨 생성

Pomodoro.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Sources/MainScene/ViewControllers/MainViewController.swift
=> [Feat] #112 Long Press로 타이머 시간 중단하기

Sources/DashBoardScene/Views/DashboardPieChartCell.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift
=> [Feat] 파이차트 정책 반영하기 

Sources/BreakScene/BreakTimerViewController.swift, Sources/MainScene/ViewControllers/MainPageViewController.swift, Sources/MainScene/ViewControllers/MainViewController.swift
close #140 
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/97924765/b7e346cc-7c0c-45e7-863b-864777b8d3d7
<br>
구현해야하는 이슈 체크리스트
=> [Feat] 타이머에 따라 화면 채우기

Pomodoro.xcodeproj/project.pbxproj, Pomodoro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
~~~swift
UIColor.pomodoro.{colorName}
// example
UIColor.pomodoro.primary500
~~~
=> [Feat] design system 추가

Pomodoro.xcodeproj/project.pbxproj, Pomodoro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/BreakScene/BreakTimerViewController.swift, Sources/MainScene/ViewControllers/ColorPaletteViewController.swift, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagCollectionViewData.swift, Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/90087719/bd97f237-7cf3-4cd2-b384-c6d581ebabee
- 컨펌버튼 적용 방법 물어보기
- 컬렉션뷰 셀 배경색 적용
=> [Feat] 태그 모달 뷰 설정완료 버튼 생성

Pomodoro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift
팝업 사용법은 아래 참고 부탁드립니다.
https://github.com/HGU-iOS-Study-Group/PomodoroDesignSystem?tab=readme-ov-file#pomodoro-popup-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0
=> [Chore] PomodoroDesignSystem 패키지 업데이트, 빌드에러 수정

Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift
close #206 #208 
close #204 #207
=> [Feat] 컬러팔레트 태그 설정 모달 화면 하나로 합치기

Pomodoro.xcodeproj/project.pbxproj, Sources/App/AppDelegate.swift, Sources/Common/Managers/OnBoardingManager.swift, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/Model/Tag.swift, Sources/SettingsScene/ViewControllers/SettingViewController.swift
=> [Feat] 홈화면 UI 수정

Sources/BreakScene/BreakTimerViewController.swift, Sources/DashBoardScene/Views/DashboardPieChartCell.swift
close #227 
렘에 있는 데이터를 파이차트에 연결하였습니다.
<br>
구현해야하는 이슈 체크리스트
=> [Fix] 대시보드 pie chart 렘 연결하기

Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/Model/Tag.swift, Sources/SettingsScene/ViewControllers/SettingViewController.swift
=> [Feat] 태그 Realm 연결

Sources/DashBoardScene/ViewControllers/DashBoardTabViewController.swift, Sources/DashBoardScene/Views/DashboardPieChartCell.swift, Sources/DashBoardScene/Views/MockData.swift, Sources/MainScene/ViewControllers/ColorPaletteViewController.swift, Sources/MainScene/ViewControllers/MainPageViewController.swift, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/Model/PomodoroRouter.swift, Sources/Model/Tag.swift
https://github.com/HGU-iOS-Study-Group/Pomodoro/issues/233
[Fix] 터치해서 설정하기 UI 겹치는 현상 고치기 #233
=> [Feat] #168 태그 부분 Realm 연결하기

Sources/MainScene/ViewControllers/MainViewController.swift
close #261 , #257 
- 타이머 실행 중에는 UserIntraction을 false로 설정함
=> [Fix] 타이머 중 시간 설정이 가능한 이슈 수정

Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/MainScene/ViewControllers/TimeSettingViewController.swift
#278 
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/122281984/7c3db1c6-2b47-4c60-9d1f-c759dca0ec24
=> [Fix] 렘에 태그 값 들어가지 않는 버그 해결

Sources/Common/Managers/DatabaseManager.swift, Sources/DashBoardScene/Views/DashboardPieChartCell.swift, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/MainScene/ViewControllers/TimeSettingViewController.swift, Sources/MainScene/Views/TagCollectionViewCell.swift, Sources/Model/Pomodoro.swift, Sources/SettingsScene/ViewControllers/SettingViewController.swift
close #297 
<video width="400" src="https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/61077215/5c709b4d-6b42-435c-a7af-53129d369b33"></video>
=> [Fix] [Bug][태그] 태그가 String으로 렘에 저장되서 나중에 불러올 때 배경색, 폰트색 못 불러오는 현상 #297

Sources/App/AppDelegate.swift, Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift
close #299
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/90087719/c378cb97-afbd-4807-bf59-0a779d6268cd
=> [Bug][태그설정] 태그가 1개 남은 상태 > 마지막 태그 삭제 > 홈 이동 > 태그 설정 재진입 시 제거한 태그들이 살아나는 현상

Sources/App/SceneDelegate.swift, Sources/BreakScene/BreakTimerViewController.swift, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/MainScene/ViewControllers/TimeSettingViewController.swift
=> [Fix] 디자인 이슈 수정

Sources/DashBoardScene/Views/DashboardPieChartCell.swift
=> [Feat] dashboard가 0일 때 UI

Sources/MainScene/ViewControllers/TagModalViewController.swift
selectedTag -> selectedButtonTag 변수명 변경
=> [fix] selectTag 중복 변수명 변경

Sources/MainScene/ViewControllers/TagModalViewController.swift
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/90087719/4f651abe-f958-4e8b-b022-c8afcc5f1647
=> [Fix] 태그선택해제 UI 수정

Sources/DashBoardScene/Views/DashboardPieChartCell.swift, Sources/MainScene/ViewControllers/TimeSettingViewController.swift
=> [Bug][시간설정] 최대 시간이 한칸 부족한 현상

Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift
close #305
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/90087719/5f76a53f-4a61-4fa3-803a-4e4add9a0cbf
close #307 
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/90087719/c0672da3-3536-4b86-9e92-a25ffc1005a1
=> [Bug][태그] 태그 삭제 버튼 누른 뒤 즉시 삭제 되지 않는 현상

Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/MainScene/ViewControllers/TimeSettingViewController.swift
이전에 포커스 타임을 설정했음에도 다시 시간 설정하려고 했을때 00:00부터 설정해야되는 버그를 해결했다.
https://github.com/HGU-iOS-Study-Group/Pomodoro/assets/122281984/06a96e81-59a6-4eed-8bcd-fe7200458483
=> [Fix][시간설정] 이전에 포커스 타임을 설정했음에도 다시 시간 설정하려고 했을때 00:00부터 설정해야되는 버그

Pomodoro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/MainScene/ViewControllers/TimeSettingViewController.swift
https://github.com/user-attachments/assets/6ef748ba-3960-441b-9f88-30c7a69ac281
#추가 
pomodoroTimeManager.resumeTimer 등 에러 사항 수정(삭제)
=> [fix] 실제 종료 시간 분에서 시로 기준을 바꿈

Sources/DashBoardScene/Views/DashboardStatusCell.swift, Sources/MainScene/ViewControllers/MainViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift, Sources/MainScene/ViewControllers/TimeSettingViewController.swift, Sources/Model/Pomodoro.swift
close #323 
https://github.com/user-attachments/assets/425177ef-d9cf-473c-98a7-736f715b7341
https://github.com/user-attachments/assets/374490bf-4268-4668-a61c-18a82a1fe185
=> [Bug] 뽀모도로 시작과 동시에 대시보드의 실패 횟수가 증가하는 현상

Sources/MainScene/ViewControllers/TimeSettingViewController.swift
https://github.com/user-attachments/assets/30c06e40-f8c6-4741-9fb9-7210b7484305
=> [Fix]휴식시간 포함한 TimeSettingViewController에 종료시간 표시

Sources/MainScene/ViewControllers/TagConfigurationViewController.swift, Sources/MainScene/ViewControllers/TagModalViewController.swift
https://github.com/user-attachments/assets/92a30455-3f3a-4b87-a88a-9bab3dbfe03d
=> [Fix] 최대 글자 수 한글 이슈 수정, UI 이슈 수정 / 태그 삭제 버튼 초기화되는 이슈 수정, 태그 추가시 적용안되는 이슈 수정
